disable_existing_loggers = true
version = 1

[formatters]
[formatters.custom]
"()" = "pennylane.logging.formatters.formatter.DefaultFormatter"

[formatters.custom2]
"()" = "pennylane.logging.formatters.formatter.AnotherLogFormatter"

[formatters.detailed]
format = "\u001B[38;4;45m[%(asctime)s][%(levelname)s][<PID %(process)d:%(processName)s>] - %(name)s.%(funcName)s()::\"%(message)s\"\u001B[0m"

[formatters.standard]
format = "[%(asctime)s] - %(name)s - %(levelname)s - %(message)s"

[filters]
[filters.LocalProcessFilter]
"()" = "pennylane.logging.filter.LocalProcessFilter"

[filters.DebugOnlyFilter]
"()" = "pennylane.logging.filter.DebugOnlyFilter"


[handlers]

[handlers.console]
class = "logging.StreamHandler"
formatter = "detailed"
level = "DEBUG"
stream = "ext://sys.stdout"

[handlers.console_custom]
class = "logging.StreamHandler"
formatter = "custom"
level = "DEBUG"
stream = "ext://sys.stdout"
filters = ["LocalProcessFilter", "DebugOnlyFilter"]


[loggers]
[loggers.jax]
handlers = ["console_custom"]
level = "DEBUG"
propagate = false

[loggers.main]
handlers = ["console_custom"]
level = "DEBUG"
propagate = false

[loggers.pennylane]
handlers = ["console_custom"]
level = "DEBUG" # Set to 1 for highest verbosity
propagate = false

[root]
handlers = ["console_custom"]
level = "DEBUG"
propagate = false
