name: Docker builds
on:
  push:
    branches:
      - master

jobs:
  base-tests:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build & test PennyLane
        run: make -f docker/Makefile build-base